### ISSUE TITLE
Gradle "Build Library" task is failing (ubuntu-latest, 1.8)

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#177] opened 2020-09-16 15:44 UTC
E.g., see https://github.com/grpc/grpc-kotlin/pull/176/checks?check_run_id=1123986930. I'm quite sure that the build failure has something to do with the doc-only change of #176 :).

```console
> Task :grpc-kotlin-stub:testClasses

> Task :grpc-kotlin-stub:test

io.grpc.kotlin.ServerCallsTest > rejectNonClientStreamingMethod PASSED
...
io.grpc.kotlin.ClientCallsTest > clientStreamingRpcCancelled STANDARD_ERROR
    Sep 16, 2020 3:36:11 PM io.grpc.internal.SerializingExecutor run
    SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@785e7e16
    io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
    	at io.grpc.Status.asRuntimeException(Status.java:524)
    	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:275)
    	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
    	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
    	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:868)
    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jamesward** [comment] 2020-09-16 17:58
The actual failed test is:
```
io.grpc.kotlin.GeneratedCodeTest > clientStreamingRpcCancellation FAILED
    io.grpc.StatusException: CANCELLED: Collection of requests completed exceptionally

        Caused by:
        kotlinx.coroutines.JobCancellationException: DeferredCoroutine was cancelled; job="coroutine#86":DeferredCoroutine{Cancelled}@2a050e45
```

But I'm not able to reproduce this locally on JDK 11.  I think we need @lowasser to investigate further.

**Comment by bshaffer** [comment] 2020-09-16 19:59
Ive seen this error intermittently and re-running the actions does the trick. It's not a great solution, I know.

**Comment by chalin** [comment] 2020-09-17 18:38
Is this related to #146? Should this issue and #146 be closed in favor of creating an issue for "Flaky tests" :)?

**Comment by jamesward** [comment] 2020-10-06 20:19
I think I've fixed this (with @saturnism's help):
https://github.com/grpc/grpc-kotlin/pull/187/files#diff-1e1ad71f3ea53efc7d27fa036922f32bL191-R198

**Comment by bshaffer** [comment] 2020-11-03 00:44
I haven't seen this error in a while so I agree it's now fixed. Thanks @jamesward !

**Closed by bshaffer** 2020-11-03 00:44 UTC
