### ISSUE TITLE
How can I generate Kotlin code instead of Java code ? 

### ISSUE THREAD

**Issue by aalexsanyan** [grpc/grpc-kotlin#132] opened 2020-06-28 00:45 UTC
I am new to Protobuf and the project I am working on is using Protobuf and it is generating to java. 
Now I want to change it to Kotlin .
Would you mind to help to change it ,so I can make it generate Kotlin code

```
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }
    plugins {
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
}

dependencies {
    api('com.google.protobuf:protobuf-lite:3.0.1')
}
`

**Comment by jamesward** [comment] 2020-06-28 19:57
grpc-kotlin will still generate the Java but it will also generate idiomatic Kotlin wrappers around it.  Here is an example Gradle build:
https://github.com/grpc/grpc-kotlin/blob/master/examples/build.gradle

**Comment by chalin** [comment] 2020-06-30 18:23
Not sure, but is this a duplicate of #64? If so, from the [README](https://github.com/grpc/grpc-kotlin/blob/master/README.md):
  > **Note:** The Kotlin protoc plugin uses the [Java protoc plugin][gen-java]
  > behind the scenes to **generate _message types_ as _Java classes_**.
  > Generation of Kotlin sources for proto messages is being discussed in
  > [protocolbuffers/protobuf#3742][].
  >
  > [protocolbuffers/protobuf#3742]: https://github.com/protocolbuffers/protobuf/issues/3742

cc @lowasser

**Closed** 2020-07-14 19:51 UTC
