### ISSUE TITLE
Cleaner object creation

### ISSUE THREAD

**Issue by pambrose** [grpc/grpc-kotlin#87] opened 2020-05-10 18:18 UTC
In the [sample code](https://github.com/grpc/grpc-kotlin/blob/master/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldClient.kt) you initialize a HelloRequest object with: 
```
val request = HelloRequest.newBuilder().setName(name).build()
```

It would be a big help if you could generate a Kotlin builder for each user protobuf object:
```
fun helloRequest(block: HelloRequest.Builder.() -> Unit): HelloRequest =
    HelloRequest.newBuilder().let {
        block.invoke(it)
        it.build()
    }
```

which would allow for much cleaner object creation:
```
 val request = helloRequest { this.name = name }
```

[One of your fellow Googlers](https://github.com/googleapis/gapic-generator-kotlin) uses this approach and it makes for less cluttered user code.

**Comment by lowasser** [comment] 2020-05-11 16:57
Duplicate of #83 and #64.

**Closed by lowasser** 2020-05-11 16:57 UTC
