### ISSUE TITLE
Can I use grpc-kotlin for mpp?

### ISSUE THREAD

**Issue by caffeine-mgn** [grpc/grpc-kotlin#140] opened 2020-07-06 08:26 UTC

**Comment by jamesward** [comment] 2020-07-06 14:31
Unfortunately not right now as the generated code is all based on Java.  But this would be awesome.  Probably quite a bit of work though.

**Comment by jamesward** [comment] 2020-07-14 20:07
Duplicate of #51

**Closed by jamesward** 2020-07-14 20:07 UTC
Labels: enhancement
