### ISSUE TITLE
Feature: Generate files in koltin

### ISSUE THREAD

**Issue by HDNAdministrator** [grpc/grpc-kotlin#379] opened 2023-02-10 17:31 UTC
Instead of creating java files from proto, kotlin files and DSLs for builders would be nice

**Comment by jamesward** [comment] 2023-02-10 17:33
Yes, Kotlin/Common protos would be great. Ultimately that'd fall on: https://github.com/protocolbuffers/protobuf
Also this is kind-of a duplicate of: https://github.com/grpc/grpc-kotlin/issues/51

**Closed by jamesward** 2023-02-10 17:33 UTC
